### ISSUE TITLE
Raspberry pi3 compatibility?

### ISSUE THREAD

**Issue by johnoly99** [AstroPrint/AstroBox#101]
Hey guys,\

Any news on the compatibility for raspberry pi 3's anytime soon?

**Comment by CoDanny** [comment]
Working on it! The live streaming video feature is currently in front.

**Comment by Archangl7** [comment]
i did perform an upgrade using a pi2 first (dist-upgrade, or whatever), and then when i booted on the pi3 it connects network wise, but only wired.

**Comment by CoDanny** [comment]
Hold tight guys. It's coming!! :)
