### ISSUE TITLE
0.8(3) not updating

### ISSUE THREAD

**Issue by sltyler1** [AstroPrint/AstroBox#102]
I flashed my SD card for my Raspberry Pi 2, and am all set up. When I click to update to 0.8(8) it just sits on 'Downloading release...' any suggestions? I have rebooted already. FYI https://www.astroprint.com/Downloads only has the older 0.8(3) version.

__________
Update: After about the 4th reboot I tried it again and it started right away.

**Comment by CoDanny** [comment]
Thanks. This is not a common problem as many people are able to upgrade. Please approach us using our [support channel](https://astroprint.zendesk.com) so we can troubleshoot your particular situation. 

If it turns out that we find an common error, we can open another ticket here.
