### ISSUE TITLE
Fix minor typo on the AstroBox WiFi screen dialog box button

### ISSUE THREAD

**Issue by DilankaW** [AstroPrint/AstroBox#103]
On the WiFi screen of the AstroBox setup....

After you enter a WiFi password and press "connect" --- there's a minor typo on this button:

![screenshot from 2016-05-10 12 28 38](https://cloud.githubusercontent.com/assets/1406947/15160011/776d39b4-16ac-11e6-9bf6-a2d0956cb2d4.png)
We are missing an '**a**' -- so, it should be: _Might be a while. Please be patient....._

**Comment by joshwhite47** [comment]
fixed
