### ISSUE TITLE
pcduino video streaming resolution not updating without page refresh 

### ISSUE THREAD

**Issue by joshwhite47** [AstroPrint/AstroBox#111]
On pcduino if you switch the resolution in settings and save, the new streaming resolution doesn’t take effect unless you refresh the page. Only effects streaming video, still pictures seem to work normally.

**Comment by CoDanny** [comment]
I don't seem to be able to reproduce this...

**Comment by CoDanny** [comment]
@joshwhite47 can reproduce it on FireFox only.
