### ISSUE TITLE
Chrome on OSX fails WebRTC check

### ISSUE THREAD

**Issue by staticfloat** [AstroPrint/AstroBox#119]
Using Chrome 51 on OSX 10.11.5, trying to stream video shows the "Oops!  Looks like streaming video is incompatible with your browser." message.

**Comment by CoDanny** [comment]
This is the expected behaviour for now. Chrome 52 is expected to support H.264 WebRTC video: 
https://astroprint.zendesk.com/hc/en-us/articles/209139946-Browser-support-for-Live-Streaming
