### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by Doubledream** [AstroPrint/AstroBox#144]
How to use the public key and private key to complete user authentication? I set up a new user's system by Django and made users register to our cloud-server.We can sign in but the logo color don't turn to blue due to the error"unable to authenticate".I thought it related to public key and private key got from cloud-server.Thank you.

**Comment by JulianGarciaCastillo** [comment]
Hello! How did you resolve the problem?

**Comment by Doubledream** [comment]
Hi！I didn't solve the problem. Could you give me some suggestion? Thank you!
