### ISSUE TITLE
Display coordinates in control page

### ISSUE THREAD

**Issue by FernandoGarcia** [AstroPrint/AstroBox#147]
Hi!

I would like to suggest you to display the  coordinates for X,Y and Z in control page like in Repetier.

Sometimes I'm adjusting the settings of my printer and is useful to know the coordinates.

As an example in my case the manufacturer says the build volume is 200 x 200 x 180 mm but moving the axis I can see that it's 198 x 198 x 195 mm.

Best regards.

**Comment by CoDanny** [comment]
At the moment this is fairly advanced and will distract from other things that are more important
