### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by FernandoGarcia** [AstroPrint/AstroBox#150]
Hi!
I was starting a print to take some images to answer your question in other issue and noticed a very strange behaviour.

After start the print via file manager the Astoprint sent the command to heat the bed as you can in the image:

![sam_1044](https://cloud.githubusercontent.com/assets/2778501/18790640/f40be3aa-8185-11e6-9400-e07f59c0f20b.jpg)

But the monitor is showing the target temperature to bed as zero and nozzle as 240°C:

![monitor](https://cloud.githubusercontent.com/assets/2778501/18790665/0d52d9ae-8186-11e6-8cf5-0f47480e67f0.JPG)

In this moment the monitor should display the target temperature to bed as 85°C and nozzle as zero.

After the bed heating is done a command to turn off the bed was sent but it's wrong the temperature should  remain as 85°C and 240°C for nozzle.

![sam_1046](https://cloud.githubusercontent.com/assets/2778501/18790862/d8c18cf2-8186-11e6-9b00-5571365892df.jpg)

The strange thing is the monitor display the right temperature to both but the info on LCD is totally different.

![monitor2](https://cloud.githubusercontent.com/assets/2778501/18790921/1780a75c-8187-11e6-86a5-4afd7c02edcd.JPG)

The print was started with the bed OFF:

![sam_1047](https://cloud.githubusercontent.com/assets/2778501/18791144/eb26b7ae-8187-11e6-839e-2bb5b0c6da9c.jpg)

I'm using a Geeetech Prusa I3 Pro B with Marlin.

I did the upgrade to version 0.9(5) yesterday, I didn't see it before. Moreover I'm new to Astroprint.

Best regards.

**Comment by CoDanny** [comment]
Does this still happen with 0.10(7)?

**Comment by FernandoGarcia** [comment]
Since I have installed a second extruder I'm not using Astroprint because the support is very poor.

I'm waiting for updates.

**Comment by CoDanny** [comment]
OK, I'll close this now. Support is coming :)
