### ISSUE TITLE
Suggestion - AstroPrint.com account link on the box dashboard.

### ISSUE THREAD

**Issue by acunyc** [AstroPrint/AstroBox#16]
I would find it very helpful to go directly to my cloud dashboard from the box.  My suggestion is a link at the top of the page "Go to AstroPrint.com account"  or "My Cloud Account" or "AstroPrint.com Dashboard."
If they are not online, once clicked it would say "you are not connected to the internet."  If they are online, it would open a new tab (or window) going to their astroprint.com dashboard.

**Comment by CoDanny** [comment]
Investigate if we can auto log the user into their astroprint account
