### ISSUE TITLE
Random Time shows up in time left section at end of print

### ISSUE THREAD

**Issue by joshwhite47** [AstroPrint/AstroBox#161]
On the last layer with a few seconds left a random time(or what seemed like a random time) showed up in the time left area. The print goes down to 0 switches to this time and then the print ends.

<img width="589" alt="screen shot 2016-10-18 at 11 45 01 am" src="https://cloud.githubusercontent.com/assets/4854972/19492483/b33e059c-952b-11e6-99f7-ae9441e0d2e7.png">

**Comment by joshwhite47** [comment]
Here is a video where this issue happens. 

https://drive.google.com/file/d/0BxCcy5TynrdaQlZwUXFBSEJ0Yk0/view?usp=sharing

**Comment by lukemaster** [comment]
In the first capture of this issue, I can see 19:38 minutes of time left. Is this the complete time left of this printing? When the progress is 0 percent, how much time left appears in Time?

**Comment by CoDanny** [comment]
Fixed on astroprint.com
