### ISSUE TITLE
Auto-Connect to printer on astrobox service startup

### ISSUE THREAD

**Issue by joshwhite47** [AstroPrint/AstroBox#185]
If I turn on a box and then see that box on astroprint.com, AP desktop, or AP mobile I see the box connected to my astroprint account but I can't print because the printer is not connected to the box. As soon as I open the local page on the astrobox the page loads and the printer connects on page load.

**Comment by CoDanny** [comment]
This has always been like this. However it might make sense that the printer connects on startup. That is a new feature.

**Comment by joshwhite47** [comment]
Yeah, I guess I've just noticed it more lately since i've been trying to look at printers from the app, and desktop software more lately. It would be nice for it to detect a connected printer without having to open that page.
