### ISSUE TITLE
Display temperature for second extruder

### ISSUE THREAD

**Issue by FernandoGarcia** [AstroPrint/AstroBox#202]
Hi!

Please add a second control bar for second extruder.

As it's now is impossible know the temperature for both extruders.

Now I have the first extruder with 66°C and the second with 154°C but I can see the temperature only for the first extruder.

![fffffffffff](https://cloud.githubusercontent.com/assets/2778501/21140222/f2292a2a-c11d-11e6-9c6b-2ce7e39599a4.JPG)

Best regards.

**Comment by JulianGarciaCastillo** [comment]
It's a feature we are  currently working. Support for multiple extruders. It will be added soon.

**Comment by highground88** [comment]
I notice this comment was a while ago, Astroprint still broken apparently in this regard on the latest current version on my Flashforge Creator Pro - or is it just me?

**Comment by CoDanny** [comment]
@highground88 Not just you. We have active branch for this

**Comment by FernandoGarcia** [comment]
Thanks for this new feature!
I'm back to Astroprint. :)
