### ISSUE TITLE
File Manager: Allow dragging and dropping of design rows

### ISSUE THREAD

**Issue by MikeRatcliffe** [AstroPrint/AstroBox#254]
It should be possible to drag design rows between categories in order to sort them more efficiently.

**Comment by CoDanny** [comment]
I don't understand this one. Is this for the AstroBox or the Astroprint Cloud

**Comment by MikeRatcliffe** [comment]
Oh, I suppose that would be Astroprint cloud... is that a different repo?

**Comment by CoDanny** [comment]
@MikeRatcliffe There's no public repo for the astroprint cloud. I can make sure your suggestion is logged though. Just wanted to clarify

**Comment by CoDanny** [comment]
Logged for astroprint cloud
