### ISSUE TITLE
If M140/M104 is in Start GCode and commented out slic3r doesn't set temperature

### ISSUE THREAD

**Issue by MikeRatcliffe** [AstroPrint/AstroBox#255]
For example, if this is in the START GCode:

```
;M117 Heating Bed and Extruder...
;M140 S80
;M104 S240
```

The parser doesn't recognize that the lines are commented out so when the file is sliced no temperatures are inserted and the printer will try to print cold.

**Comment by CoDanny** [comment]
The slicing process happens on the AstroPrint Cloud. Logged there.
