### ISSUE TITLE
Max fan speed is ignored

### ISSUE THREAD

**Issue by maximeaubaret** [AstroPrint/AstroBox#272]
# Expected behavior
When the Maximum Fan Speed is set to 60%, the fan speed should not go higher than 60%.

# Current behavior
The max speed setting is set to 60%, but the fan is still going at full speed.
I was able to confirm it by downloading the GCode file and finding a`M106 S255` command.

# Steps to Reproduce
Start a print with the following cooling settings:
<img width="479" alt="screen shot 2017-05-21 at 15 11 57" src="https://cloud.githubusercontent.com/assets/364453/26284298/db7f099c-3e37-11e7-832b-061ffaf77f80.png">

**Comment by CoDanny** [comment]
I'll file this problem in our online slicer and close here. Thanks for reporting.
