### ISSUE TITLE
Cant upload stl from Android 

### ISSUE THREAD

**Issue by olskar** [AstroPrint/AstroBox#277]
![screenshot_20170524-160513](https://cloud.githubusercontent.com/assets/18314560/26407319/0e6fe87a-409b-11e7-9a48-d39d238f86e1.png)

**Comment by CoDanny** [comment]
did the file have a .stl extension? I just tried this and it worked. Which android version was it?

**Comment by olskar** [comment]
This was an error on my end, sorry.

**Comment by CoDanny** [comment]
No worries, just curious, what was it?
