### ISSUE TITLE
Some serials ports are not listed in the connection screen

### ISSUE THREAD

**Issue by CoDanny** [AstroPrint/AstroBox#281]
User has reported (Ticket #2556) that when connecting a printer, nothing shows up in the list of available ports. However when editing config.yaml and adding the following port it works:

```
serial: 
  port: /dev/ttyACM0 
  baud: 115200
```

We need to figure out why the port is not in the list.

**Comment by MikeRatcliffe** [comment]
More info:
https://forum.astroprint.com/t/web-ui-not-showing-connection-to-prusa-i3-mk2s/2398

**Comment by CoDanny** [comment]
fixed with https://github.com/AstroPrint/AstroBox/commit/74a79cf88cf6649f681ae61ec774297908b27b92
