### ISSUE TITLE
Option to flip camera so camera can be inverted upside on bed.

### ISSUE THREAD

**Issue by rhys100** [AstroPrint/AstroBox#287]
Is it possible to invert the webcam image to its able to be mounted upside down

**Comment by CoDanny** [comment]
Not at the moment but it's already logged as an issue.

**Comment by CoDanny** [comment]
duplicate of #75

**Comment by Cyphen-Cyn** [comment]
Where is the option to flip camera?

**Comment by CoDanny** [comment]
@Cyphen-Cyn It's not implemented yet. This was closed because the same request already exists on #75
