### ISSUE TITLE
G-Code upload does not calculate correct number of layers

### ISSUE THREAD

**Issue by joshwhite47** [AstroPrint/AstroBox#29]
Printing screen shows the incorrect number of total layers.

![screen shot 2014-10-07 at 1 26 12 pm](https://cloud.githubusercontent.com/assets/4854972/4549716/6de015a8-4e60-11e4-8820-36df5d509663.png)

Also had this issue... same slic3r settings but different stl.

![screen shot 2014-10-07 at 2 32 31 pm](https://cloud.githubusercontent.com/assets/4854972/4550775/f0163f58-4e69-11e4-97d1-73c97c897345.png)

**Comment by KissmanCZ** [comment]
And this is feature or bug...? Two years later Astrobox still not counting gcode layers... why?

**Comment by CoDanny** [comment]
If you use our slicer or print a second time, they layers will be there.

**Comment by KissmanCZ** [comment]
I will on less complicated parts (i understand what is the point of using your slicer). But I have very complicated parts, which cannot be sliced with your slicer for succesful print - srry. Than what?

**Comment by CoDanny** [comment]
valid point, it will ( or should ) pick up the number of layers when the first completed print is done. At some point we can add the layer counter to the astrobox analyzing task but at the moment is hasn't been a problem for most people.

**Comment by KissmanCZ** [comment]
And how AstroBox know about number of layers? Some added gcode from you slicer? Can i add this to my code by "hand" for my complicated prints? I am slicing with Simplify3D, i need diff. speed for each layer, diff. temp for each layer, diff. endpoints for each layer and many more setting "per layer based" and really want create nice timelapses.

**Comment by robvoi** [comment]
I have the same problem. I would like to see amount of layers and print time left too. Both doesn't work for uploaded gcode.

**Comment by arcmatt** [comment]
I would really like to see this too, knowing how many layers are remaining is pretty important. I would be happy if I could simply add it to my own gcode to have Astroprint use. Also, knowing what layer a print is on and how many are remaining would make the calculated print error less annoying.
