### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by forum999** [AstroPrint/AstroBox#321]
Enable plugins like Octoprint to allow for filament sensors

or ideally save u the work and allow octoprint compatability o use their plugins to save the work of writing new script... Astroprint severly lacks in this area

**Comment by CoDanny** [comment]
We will offer this in the future. Also this: https://github.com/AstroPrint/OctoPrint-AstroPrint

**Comment by forum999** [comment]
hi thats great but i am a diehard astroprint user and often promote it over octiprint which i am not keen on at all, i would much prefer the ability to create these scripts or impliment existing ones directly into astroprint , especially the filament sensor

**Comment by CoDanny** [comment]
Thanks :) We will release a plugin API early in 2018
