### ISSUE TITLE
Investigate using the internal RPi3 WiFi as concurrent AP, Client Mode

### ISSUE THREAD

**Issue by CoDanny** [AstroPrint/AstroBox#325]
This will allow for the removal of the requirement of having to have the extra dongle.

More info here: https://albeec13.github.io/2017/09/26/raspberry-pi-zero-w-simultaneous-ap-and-managed-mode-wifi/

**Comment by Rigid3D** [comment]
This method works very well on Octoprint/Pi Zero W. Tested on Raspberry Pi Zero W. 

But it was not succesful on Astroprint/Pi 3. I couldn't manage to login system without a wifi dongle on pi Zero W. :) and tested with Pi 3.

**Comment by CoDanny** [comment]
Another (easier?) way to get the second interface up:
https://www.raspberrypi.org/forums/viewtopic.php?t=138730#p936518

Still need to make changes in AP software to use it.

**Comment by CoDanny** [comment]
I'm unable to connect to an external WiFi while connected to the AP. This is likely not going to work for us. It appears that for this to work the external WiFi settings needs to be hardcoded in the /etc/interfaces which won't work for us.
