### ISSUE TITLE
Update not available - installed 0.10(11) - available 0.10.19

### ISSUE THREAD

**Issue by BjoernKellermann** [AstroPrint/AstroBox#356]
My RPi 2 has AstroBox 0.10(11) installed using the provided SD card image.

Today I "check for updates" and got the message "No Updates available"
Following the release notes, there is a new version 0.10.19. But there isnot feature to "update".

Pop-up has only two options:
- Cancel
- Re-install, which does not update...

**Comment by CoDanny** [comment]
Pre-releases are not available for over-the-air uploads.
