### ISSUE TITLE
option to turn off annoying check box after print cancel

### ISSUE THREAD

**Issue by forum999** [AstroPrint/AstroBox#365]
We need an option to disable the annoying check box in settings after a print cancel.

its a pain in the arse that astroprint already doesnt have a heat hold setting but you have to scroll down on small screens like my pi's 5" screen to cancel it off then scroll back up to try and catch the heat sliders to keep them at temp.

**Comment by CoDanny** [comment]
You can simply close this dialog, you don't need to answer it
