### ISSUE TITLE
RASP Pi ZERO MK3 Loses access key / connection on Octoprint Plugin

### ISSUE THREAD

**Issue by rhys100** [AstroPrint/AstroBox#369]
Hi, I am not sure what variables are at play but I have the following Setup x2 and both have the same issue

RASP PI ZERO integrated into Prusa MK3 running 1.3.6 octoprint firmware and Astroprint Firmware.

Every day I need to goto the astroprint plugin tab and re input my api key and link them again.

I am not sure if the reset button on MK3 or other variables are at play but this is very annoying :)

**Comment by CoDanny** [comment]
@rhys100 For plugin related issues please open them here: https://github.com/AstroPrint/OctoPrint-AstroPrint/issues
