### ISSUE TITLE
Refreshing the page does not load new gcodes, but refreshing the list does.

### ISSUE THREAD

**Issue by acunyc** [AstroPrint/AstroBox#37]
I'm not sure if this is simple or not, but here is the issue I ran into:

I created a few new slices on AstroPrint.com, then went to my AstroBox console and of course did not see them.  So, I figured I needed to refresh the page.  It was only after about 10 minutes of trying various things that I realized I had to hit the refresh icon for the list.

I feel that the UX would be better for users if a page refresh also refreshed the list.

**Comment by CoDanny** [comment]
This was fixed a while back
