### ISSUE TITLE
Multiple Printer Issue

### ISSUE THREAD

**Issue by forum999** [AstroPrint/AstroBox#370]
Since the latest build if i have both my printers turned on and both my raspberry pi's connected to my account i can only see one printer in the monitor tab instead of being able to select one or the other? it used to be when i went to clicked monitor at https://cloud.astroprint.com/connected id be able to see the 2 printers with green buttons below that said camera/controls, now it only shows the one thats printing and you can not access the other printer in any way if a print is in progress, sort of defeats the object please can you investigate this

**Comment by CoDanny** [comment]
HI @forum999, this needs to be troubleshot first. I'm not yet sure it's a problem on our end (it could be but I would expect more than 1 report). Let's open a ticket at https://astroprint.zendesk.com to troubleshot this. If it ends up being a problem, I'll reopen the ticket.
