### ISSUE TITLE
filament sensor

### ISSUE THREAD

**Issue by forum999** [AstroPrint/AstroBox#385]
can you add the option for a filament sensor that triggers m600 or pause and wait for filament change command when triggered?

octoprints had this for a while but i much prefer astroprint so would like to see this added if possible

**Comment by CoDanny** [comment]
already filed under #217

**Comment by forum999** [comment]
Great but is this something intended to be developed or is there an approx timescale as to when its likely to be added?

**Comment by CoDanny** [comment]
Yes it will be developed. Does OP use a plugin for this? or is it supported in the core software?

**Comment by forum999** [comment]
Its a plugin, im hoping this makes it easier to intragrate into astro
