### ISSUE TITLE
Underscores seem to not work for .local addresses

### ISSUE THREAD

**Issue by acunyc** [AstroPrint/AstroBox#40]
Currently in the setup process, when naming the box, it is possible to use underscores.

I tried this several times and had the same problem occur, here is an example:
- I named my astrobox:  astroprint_amazeballs
- Everything worked great with the initial use of the box (it was technically still operating via astrobox.local).
- After rebooting, I could not get to it from astroprint_amazeballs.local at all.  (I tried with http://, without, etc.)
- If I had configured the wifi, it meant that I had to reflash the box, there wasn't another way to get to it.  Perhaps if I checked at AstroPrint.com I could've found the IP.
- When I tried it without configuring wifi, I could connect to astroprint_amazeballs hotspot and use 10.10.0.1 to get to it.  But I still could not connect via a .local address.

The quick and simple solution would likely be to remove the ability to use underscores for the box name.

**Comment by pelrun** [comment]
Underscores are illegal in hostnames, so restricting the box name to the valid set (letters,digits and hyphen) is really the only possible fix.
