### ISSUE TITLE
Control movement using different network via app

### ISSUE THREAD

**Issue by FernandoGarcia** [AstroPrint/AstroBox#411]
Hi!

Why I can't control movements  using a different network via app?

I can control the temperature but I can't move the axis why?

I have two routers and my phone is connected to one and the printer to another but the printer IP is reachable from my phone.

![20180528_122313](https://user-images.githubusercontent.com/2778501/40621381-ebdab010-6272-11e8-8965-6b3699a4859a.jpg)

Best regards.

**Comment by FernandoGarcia** [comment]
In fact even in the same network this message appears.

**Comment by CoDanny** [comment]
please no questions or issues for products other than the AstroBox. You can always use our forums or reach out of us via our support channel
