### ISSUE TITLE
Heating don't stops after cancel a print

### ISSUE THREAD

**Issue by FernandoGarcia** [AstroPrint/AstroBox#420]
Hi!

Actually the heaters are turned off only after the temperature reach the target.

The heating should stops immediately after cancel a print I think.

Best regards.

**Comment by CoDanny** [comment]
At the moment this isn't how printers work. When you issue a heat and wait command, the printer won't receive another command until the temperature is reached. We send the cool off command inmediately but the printer is blocked. Canceling while heating up is still a problem in some Marlin/Repetier based printers.
