### ISSUE TITLE
GPIO TTL SERIAL - No Connection to Printer

### ISSUE THREAD

**Issue by Rigid3D** [AstroPrint/AstroBox#430]
With the latest version of Astrobox 0.13(16), printer is not detected and can not connect to the printer via pin 14 and 15 on GPIO. Port is not detected.

It works flawlessly on Astrobox 0.10(9).

Board is Raspberry Pi 3 and printer firmware is Marlin 1.1.9

There is no record on serial log.

Astrobox.log related record is

astroprint.printer - WARNING - Unable to connect to any available port [] with baudrate [115200]

**Comment by CoDanny** [comment]
I think I have the fix. Could you please run these commands in your box to verify it?

```
# sudo wget https://raw.githubusercontent.com/AstroPrint/AstroBox/fix-430/src/astroprint/printer/marlin/__init__.py /AstroBox/src/astroprint/printer/marlin/__init__.py
# sudo service astrobox restart
```

Then see if it works.

**Comment by CoDanny** [comment]
@Rigid3D Were you able to verify that my changes helped you?

**Comment by CoDanny** [comment]
@Rigid3D I wanted to see if we should merge this in the codeline. Were you able to verify that it works?
