### ISSUE TITLE
Print Queue: Unable to print file 

### ISSUE THREAD

**Issue by CoDanny** [AstroPrint/AstroBox#437]
The file was added to the queue using the cloud, then I tried to print from the box and I got this error

<img width="1330" alt="screen shot 2018-10-22 at 7 00 58 pm" src="https://user-images.githubusercontent.com/542760/47324215-f27d4080-d62c-11e8-9758-649a022a0cda.png">

**Comment by julianCast** [comment]
Unable to reproduce it so far.

**Comment by CoDanny** [comment]
Seems to not happen in latest version of the software
