### ISSUE TITLE
Printing frozen 

### ISSUE THREAD

**Issue by julianCast** [AstroPrint/AstroBox#439]
During a printing, after a random time, the printer stop printing and the nozzle doesn't move from whenever it is. It can't be resumed.It happens any time, either right in the begining or after 6 hours.

Marlin driver no experimental.
Marlin firmware 1 and 2.

<img width="481" alt="screenshot 2018-11-05 at 10 59 38" src="https://user-images.githubusercontent.com/559677/47991610-f3ad7380-e0ea-11e8-996e-a41ae0d31e9d.png">
<img width="516" alt="screenshot 2018-11-05 at 10 59 53" src="https://user-images.githubusercontent.com/559677/47991611-f4460a00-e0ea-11e8-98e7-8cc2ffde03aa.png">

**Comment by CoDanny** [comment]
It appears that the firmware stopped sending responses
