### ISSUE TITLE
Instantaneous Temperature changes on the monitor.

### ISSUE THREAD

**Issue by rainbowEagle** [AstroPrint/AstroBox#490]
When we use Astro-box the application shows a constant temperature of extruder and bed. For example, while the bed is heating, it(application) doesn't show the gradual increase in the temperature of the extruder or bed. We should manually check if they heated up.
My question: how can we check this gradual rise in temperature on the monitor?

**Comment by CoDanny** [comment]
I'm not sure what you mean. We report temperature changes every 2-3 seconds.

**Comment by rainbowEagle** [comment]
works now. thanks.
