### ISSUE TITLE
Utilities menu is not getting current status from printer

### ISSUE THREAD

**Issue by FernandoGarcia** [AstroPrint/AstroBox#492]
Hi!

When utilities menu is opened it doesn't get the current values from printer.

I have configured on rotary button a speed of 80% but utilities menu sends a value of 100% when it's opened.

So I have to send 80% again.

The same for print flow.

Best regards.

**Comment by julianCast** [comment]
Currently, the marlin firmware doesn't allow us to know the print speed, print flow or even fan speed. The moment they implement that we will reopen this to match those values in our system.

Thank you!

**Comment by FernandoGarcia** [comment]
I think it should stay open as feature request because it will be forgotten on time.
