### ISSUE TITLE
Show a more clear skip link in printer model selection setup step

### ISSUE THREAD

**Issue by CoDanny** [AstroPrint/AstroBox#504]
A skip button should show all the time on this screen in case network is not setup or the printer is not found.

![F9E18E87-B823-421C-A5A0-76B910C769B2](https://user-images.githubusercontent.com/542760/56266592-e14d5200-60ec-11e9-8d95-7ea9f8926f8c.png)

**Comment by CoDanny** [comment]
The following error appears in the console:


![B550419B-81DC-4D49-BC96-CAEC50E7F066](https://user-images.githubusercontent.com/542760/56493531-adf53380-64ef-11e9-890a-94534ba3d9be.jpeg)

**Comment by julianCast** [comment]
fixes https://github.com/AstroPrint/AstroBox/commit/029179b6ce97306c901b8a45081cccf2a61d0273
