### ISSUE TITLE
Printer not running g29 correctly

### ISSUE THREAD

**Issue by Blitzacer** [AstroPrint/AstroBox#505]
After the update to V0.16(2) my cr-10 with a capacitive Z sensor doesn't g28 and g29 correctly. It just moves the Z up and does not probe at all. It used to work but now it doesn't.

**Comment by CoDanny** [comment]
For these types of logs we need to see logs, please follow the instructions here to open a ticket and send logs: https://astroprint.zendesk.com/hc/en-us/articles/360025754251-Sending-logs-to-AstroPrint
