### ISSUE TITLE
webRTC not working on insecure origins [chrome 74]

### ISSUE THREAD

**Issue by julianCast** [AstroPrint/AstroBox#512]
- Cause: https://groups.google.com/forum/#!topic/discuss-webrtc/QUdwwa-83K8
- Posible solution: https://gist.github.com/tetkuz/0c038321d05586841897
- Temporarly solution: Show message asking to user to add the device url to be treated as secure using chrome flags.

**Comment by CoDanny** [comment]
closed with #516
