### ISSUE TITLE
Not receiving printing finished emails 

### ISSUE THREAD

**Issue by jefft0825** [AstroPrint/AstroBox#564]
Logged into my account.   It’s setup to receive them but I haven’t been getting them for a few weeks now.   It might have been when I updated to the newest version but not sure.  Any suggestions?

**Comment by CoDanny** [comment]
Do you see your completed print jobs in the cloud's print history section?

**Comment by jefft0825** [comment]
Under the cloud section in file manager?     I have never been able to see
completed print history

**Comment by jefft0825** [comment]
Just found what you were asking about.   There is some print history there
but it stopped on 4/29.

**Comment by CoDanny** [comment]
I think this might be a problem related to you box and not a product issue. I'll close this issue as this is for product issues. Please open a support ticket with us so we can take a deeper look at this.
