### ISSUE TITLE
Internet setup causes an Internal Server Error

### ISSUE THREAD

**Issue by MiniguyBrendan** [AstroPrint/AstroBox#59]
When I try to set up internet, this happens:

![image](https://cloud.githubusercontent.com/assets/6320771/7383183/dd83d6d8-ede8-11e4-86da-af81336ec6b5.png)

If I skip it, nothing functions properly.

Thoughts?

**Comment by CoDanny** [comment]
Unfortunately we don't currently support the AstroBox project on Windows Machines. Linux or Mac are supported.

**Comment by MiniguyBrendan** [comment]
Wait, you mean you can't set up the astrobox from a windows machine? That would have been nice to know when I reset my raspberry pi for it...

**Comment by CoDanny** [comment]
No, I had assumed that you're fiddling with the open source project as you entered your ticket here. We do support setting up and accessing a box from Windows. Product related support tickets should go here. https://astroprint.zendesk.com

Please enter a ticket there and we will help you get you astrobox working.

**Comment by MiniguyBrendan** [comment]
Okay, one more thing, it's not an AstroBox from you guys, it's my Raspberry Pi. Thanks for the help!

**Comment by MiniguyBrendan** [comment]
OK, I just read about the WiFi dongles. I'm assuming mine must not be supported. The RTL8192CU does seems to have concurrent mode, but it's not working once I get to that step.

**Comment by CoDanny** [comment]
We support RPis just the same :) It would be best if we move this conversation to our support system. Could you open a ticket there?

**Comment by MiniguyBrendan** [comment]
Sure, sorry about that! I'm off! Last question, will the responses be as quick as they were here?

**Comment by CoDanny** [comment]
As quick and by the same person ;)

**Comment by MiniguyBrendan** [comment]
Awesome, thanks! Good to know!
