### ISSUE TITLE
Suggestion: Ability to resize model before slicing

### ISSUE THREAD

**Issue by MiniguyBrendan** [AstroPrint/AstroBox#63]
If this is already possible, I'm going to feel silly, but I don't see anywhere to resize the model. I have a PrintrBot Simple, so most models needs to be scaled down. It's a pain to have to either slice in Cura then upload the gcode, or to resize in tinkercad and then upload. I'd make a pull request, but this goes beyond my abilities. 

Resizing models is pretty crucial to 3D printing, in my opinion.

**Comment by CoDanny** [comment]
We have that feature currently under development. It should be released next week. This is an astroprint.com feature though
